# Generated by Django 4.2.19 on 2025-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prova", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phoneNumber",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
