# Generated by Django 4.2.19 on 2025-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prova", "0002_person_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
