# Generated by Django 4.2.19 on 2025-03-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prova", "0003_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 18, 9, 39, 31, 156493, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="phoneNumber",
            field=models.CharField(default="", max_length=10),
        ),
    ]
