# Generated by Django 4.2.19 on 2025-03-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prova", "0004_person_birth_date_alter_person_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateTimeField(),
        ),
    ]
